// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD96JSQkuS1oHRIkN8trXr5AGI3hG5KRO4',
    appId: '1:573547430619:web:2a71621fb4f4115a6842fe',
    messagingSenderId: '573547430619',
    projectId: 'schoolrideapp-69b97',
    authDomain: 'schoolrideapp-69b97.firebaseapp.com',
    storageBucket: 'schoolrideapp-69b97.appspot.com',
    measurementId: 'G-27Z4T7XPS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQdZ56FbwqtcenKKNBcsXV-odA_KsJHnA',
    appId: '1:573547430619:android:fa7565a34cd4d2b56842fe',
    messagingSenderId: '573547430619',
    projectId: 'schoolrideapp-69b97',
    storageBucket: 'schoolrideapp-69b97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQMGZhMxzn9Qu0M_oCaiU24EKjcjjc76o',
    appId: '1:573547430619:ios:111721d5c1bfdcc46842fe',
    messagingSenderId: '573547430619',
    projectId: 'schoolrideapp-69b97',
    storageBucket: 'schoolrideapp-69b97.appspot.com',
    androidClientId: '573547430619-hp8bvmj0suj03bdvkf510pkgfm3g4kjq.apps.googleusercontent.com',
    iosClientId: '573547430619-lpjusjvi62gtfjjto0rlf8fs6fgq5l83.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQMGZhMxzn9Qu0M_oCaiU24EKjcjjc76o',
    appId: '1:573547430619:ios:111721d5c1bfdcc46842fe',
    messagingSenderId: '573547430619',
    projectId: 'schoolrideapp-69b97',
    storageBucket: 'schoolrideapp-69b97.appspot.com',
    androidClientId: '573547430619-hp8bvmj0suj03bdvkf510pkgfm3g4kjq.apps.googleusercontent.com',
    iosClientId: '573547430619-lpjusjvi62gtfjjto0rlf8fs6fgq5l83.apps.googleusercontent.com',
    iosBundleId: 'com.example.project3',
  );
}
